version: '2.1'
services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: 'test_task_db'
       MYSQL_USER: 'test_task'
       MYSQL_PASSWORD: 'psswd123'
       MYSQL_ROOT_PASSWORD: 'psswd123'
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0.9
    ports:
      - "6379:6379"
    volumes:
      - ./ci/redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  test_task:
    build:
      context: .
      dockerfile: ./ci/web/Dockerfile
    volumes:
      - "./web:/src"
    command: "sh startup_commands.sh"
    ports:
      - "8010:8010"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      dockerfile: ./ci/worker/Dockerfile
    volumes:
      - "./web:/src"
    command: "celery -A test_task worker -B"
    depends_on:
      - db
      - redis