version: '2.1'
services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: 'test_task_db'
       MYSQL_USER: 'test_task'
       MYSQL_PASSWORD: 'psswd123'
       MYSQL_ROOT_PASSWORD: 'psswd123'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "test_task"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:5.0.9
    ports:
      - "6379:6379"
    volumes:
      - ./ci/redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  test_task:
    build:
      context: .
      dockerfile: ./ci/web/Dockerfile
    volumes:
      - "./web:/src"
    command: "sh startup_commands.sh"
    ports:
      - "8010:8010"
    healthcheck:
      test: curl --fail -s http://localhost:8010/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 30
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  worker:
    build:
      context: .
      dockerfile: ./ci/worker/Dockerfile
    volumes:
      - "./web:/src"
    command: "celery -A test_task worker -B"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      test_task:
        condition: service_healthy